project: 
  type: website
  
website: 
  google-analytics: G-ML1E5YYLV4

  page-navigation: true
  title: "IJC - Bit Workshops page" 
  site-url: "https://ijcbit.github.io/Workshops/" 
  repo-url: https://github.com/ijcBIT/Workshops 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By IJC-Bit, 2022"
    
  sidebar:
    logo: "data/img/hex.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.carrerasresearch.org/en/bioinformatics-unit_130420
        text: "IJC-BIT"
      - icon: github
        href:  https://github.com/ijcBIT/Workshops 
        text: "Workshops website"
 

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
     
      - section: Trainings
        contents: 
          - href: Trainings/linux_intro.qmd
            text: Introduction to Linux
          - section: Introduction to R
            contents: 
                - href: Trainings/Introduction_to_R/2quarto.qmd
                  text: 2quarto
                - href: Trainings/Introduction_to_R/R_intro.qmd
                  text: Introduction to R
          



format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto

  
