on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    # container: izarvillasante/dockerfiles:main
    steps:
      - name: Check out repository
        uses: actions/checkout@v3 
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      # add software dependencies here
      - uses: r-lib/actions/setup-r@v3
        with:
          # uses the RStudio Package Manager
          use-public-rspm: true 
          
      - name: Install terra deps
        run: sudo apt-get install -y libgdal-dev libgeos-dev libproj-dev libproj-dev
        
      # imports an action from another repository, 
      # that deals with the dependencies
      - uses: r-lib/actions/setup-r-dependencies@v3
        with: 
          packages: |
            any::rmarkdown

      - uses: r-lib/actions/setup-renv@v3
          
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      
